version: '3.8'

services:
 backend:
  build:
   context: ./recommender-back/
   dockerfile: Dockerfile
  environment:
   REQUEST_ORIGIN: http://localhost:3000
  ports:
   - 5000:5000
  command:
   flask run --host=0.0.0.0
 
 frontend:
  build:
   context: ./recommender-front/
   dockerfile: Dockerfile
  env_file:
   - ./recommender-front/.env.local
  ports:
   - 3000:3000
