version: '3.9'

services:
  mongodb:
    image: "mongodb/mongodb-community-server:latest"
    ports:
      - "27017:27017"
    volumes:
      - "mongo-test:/data/db"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 20s

  background_services:
    image: "greener-paths-background_services:latest"
    depends_on:
      mongodb:
        condition: "service_healthy"
        restart: true
    healthcheck:
      test: bash -c "[ -f /intial_aqi_update_true ]"
      interval: 60s
      timeout: 10s
      retries: 20
      start_period: 0s
    volumes:
      - "graphhopper_data:/graphhopper_data"

  graphhopper:
    image: "activity-recommender/graphhopper:latest"
    command: "--input /graphhopper/data/helsinki.osm.pbf --config /graphhopper/data/config.yml --graph-cache /graphhopper/data/graph_cache --port 8989 --host 0.0.0.0"
    depends_on:
      background_services:
        condition: "service_healthy"
    ports:
      - "8989:8989"
      - "8990:8990"
    volumes:
      - "graphhopper_data:/graphhopper/data"

  backend:
    build:
      context: ./recommender-back/
      dockerfile: Dockerfile
    env_file:
      - ./recommender-back/.env
    environment:
      REQUEST_ORIGIN: http://localhost:3000
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./recommender-front/
      dockerfile: Dockerfile
    env_file:
      - ./recommender-front/.env.local
    ports:
      - 3000:3000

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  mongo-test:
  graphhopper_data:
