# Runs frontend and backend tests on every pull request and when pull request is pushed to main
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Poetry
        run: |
          cd recommender-back
          pip install poetry
      - name: Install dependencies
        run: |
          cd recommender-back
          poetry install
      - name: Run backend tests
        run: |
          cd recommender-back
          poetry run pytest

  build_front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.2.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.2.0
      - name: Install Node
        run: |
          cd recommender-front
          npm ci
      - name: Run frontend tests
        run: |
          cd recommender-front
          npm test
