name: production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Poetry
        working-directory:
          ./recommender-back
        run: pip install poetry
      - name: Install dependencies
        working-directory:
          ./recommender-back
        run: poetry install
      - name: Run backend tests
        working-directory:
          ./recommender-back
        run: |
          poetry run coverage run --branch -m pytest
